import { buildAssetUrl } from "@/lib/assets";

export type CountryInfo = {
  code: string;
  name: string;
  region: string;
};

export const UNKNOWN_COUNTRY: CountryInfo = {
  code: "XX",
  name: "Sin país",
  region: "Otros",
};

export const FLAG_CODES = [
  "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ",
  "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS",
  "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN",
  "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE",
  "EG", "EH", "ER", "ES", "ET", "EU", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "gb-eng",
  "gb-nir", "gb-sct", "gb-wls", "GD", "GE", "GF", "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ",
  "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HM", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM",
  "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN",
  "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY",
  "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS",
  "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP",
  "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT",
  "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI",
  "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ", "TC", "TD", "TF",
  "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM",
  "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "XK", "xk", "YE", "YT",
  "ZA", "ZM", "ZW"
];

const COUNTRY_OVERRIDES: Record<string, Omit<CountryInfo, "code">> = {
  AD: { name: "Andorra", region: "Europa" },
  AE: { name: "Emiratos Árabes Unidos", region: "Asia" },
  AF: { name: "Afganistán", region: "Asia" },
  AG: { name: "Antigua y Barbuda", region: "América Central" },
  AI: { name: "Anguila", region: "América Central" },
  AL: { name: "Albania", region: "Europa" },
  AM: { name: "Armenia", region: "Asia" },
  AO: { name: "Angola", region: "África" },
  AQ: { name: "Antártida", region: "Antártida" },
  AR: { name: "Argentina", region: "América del Sur" },
  AS: { name: "Samoa Americana", region: "Oceanía" },
  AT: { name: "Austria", region: "Europa" },
  AU: { name: "Australia", region: "Oceanía" },
  AW: { name: "Aruba", region: "América Central" },
  AX: { name: "Islas Åland", region: "Europa" },
  AZ: { name: "Azerbaiyán", region: "Asia" },
  BA: { name: "Bosnia y Herzegovina", region: "Europa" },
  BB: { name: "Barbados", region: "América Central" },
  BD: { name: "Bangladés", region: "Asia" },
  BE: { name: "Bélgica", region: "Europa" },
  BF: { name: "Burkina Faso", region: "África" },
  BG: { name: "Bulgaria", region: "Europa" },
  BH: { name: "Baréin", region: "Asia" },
  BI: { name: "Burundi", region: "África" },
  BJ: { name: "Benín", region: "África" },
  BL: { name: "San Bartolomé", region: "América Central" },
  BM: { name: "Bermudas", region: "América del Norte" },
  BN: { name: "Brunéi", region: "Asia" },
  BO: { name: "Bolivia", region: "América del Sur" },
  BQ: { name: "Caribe Neerlandés", region: "América Central" },
  BR: { name: "Brasil", region: "América del Sur" },
  BS: { name: "Bahamas", region: "América Central" },
  BT: { name: "Bután", region: "Asia" },
  BV: { name: "Isla Bouvet", region: "Antártida" },
  BW: { name: "Botsuana", region: "África" },
  BY: { name: "Bielorrusia", region: "Europa" },
  BZ: { name: "Belice", region: "América Central" },
  CA: { name: "Canadá", region: "América del Norte" },
  CC: { name: "Islas Cocos", region: "Asia" },
  CD: { name: "República Democrática del Congo", region: "África" },
  CF: { name: "República Centroafricana", region: "África" },
  CG: { name: "República del Congo", region: "África" },
  CH: { name: "Suiza", region: "Europa" },
  CI: { name: "Costa de Marfil", region: "África" },
  CK: { name: "Islas Cook", region: "Oceanía" },
  CL: { name: "Chile", region: "América del Sur" },
  CM: { name: "Camerún", region: "África" },
  CN: { name: "China", region: "Asia" },
  CO: { name: "Colombia", region: "América del Sur" },
  CR: { name: "Costa Rica", region: "América Central" },
  CU: { name: "Cuba", region: "América Central" },
  CV: { name: "Cabo Verde", region: "África" },
  CW: { name: "Curazao", region: "América Central" },
  CX: { name: "Isla de Navidad", region: "Asia" },
  CY: { name: "Chipre", region: "Europa" },
  CZ: { name: "República Checa", region: "Europa" },
  DE: { name: "Alemania", region: "Europa" },
  DJ: { name: "Yibuti", region: "África" },
  DK: { name: "Dinamarca", region: "Europa" },
  DM: { name: "Dominica", region: "América Central" },
  DO: { name: "República Dominicana", region: "América Central" },
  DZ: { name: "Argelia", region: "África" },
  EC: { name: "Ecuador", region: "América del Sur" },
  EE: { name: "Estonia", region: "Europa" },
  EG: { name: "Egipto", region: "África" },
  EH: { name: "Sahara Occidental", region: "África" },
  ER: { name: "Eritrea", region: "África" },
  ES: { name: "España", region: "Europa" },
  ET: { name: "Etiopía", region: "África" },
  EU: { name: "Unión Europea", region: "Europa" },
  FI: { name: "Finlandia", region: "Europa" },
  FJ: { name: "Fiyi", region: "Oceanía" },
  FK: { name: "Islas Malvinas", region: "América del Sur" },
  FM: { name: "Micronesia", region: "Oceanía" },
  FO: { name: "Islas Feroe", region: "Europa" },
  FR: { name: "Francia", region: "Europa" },
  GA: { name: "Gabón", region: "África" },
  GB: { name: "Reino Unido", region: "Europa" },
  "gb-eng": { name: "Inglaterra", region: "Europa" },
  "gb-nir": { name: "Irlanda del Norte", region: "Europa" },
  "gb-sct": { name: "Escocia", region: "Europa" },
  "gb-wls": { name: "Gales", region: "Europa" },
  GD: { name: "Granada", region: "América Central" },
  GE: { name: "Georgia", region: "Asia" },
  GF: { name: "Guayana Francesa", region: "América del Sur" },
  GG: { name: "Guernsey", region: "Europa" },
  GH: { name: "Ghana", region: "África" },
  GI: { name: "Gibraltar", region: "Europa" },
  GL: { name: "Groenlandia", region: "América del Norte" },
  GM: { name: "Gambia", region: "África" },
  GN: { name: "Guinea", region: "África" },
  GP: { name: "Guadalupe", region: "América Central" },
  GQ: { name: "Guinea Ecuatorial", region: "África" },
  GR: { name: "Grecia", region: "Europa" },
  GS: { name: "Georgia del Sur y las Islas Sandwich del Sur", region: "Antártida" },
  GT: { name: "Guatemala", region: "América Central" },
  GU: { name: "Guam", region: "Oceanía" },
  GW: { name: "Guinea-Bisáu", region: "África" },
  GY: { name: "Guyana", region: "América del Sur" },
  HK: { name: "Hong Kong", region: "Asia" },
  HM: { name: "Islas Heard y McDonald", region: "Antártida" },
  HN: { name: "Honduras", region: "América Central" },
  HR: { name: "Croacia", region: "Europa" },
  HT: { name: "Haití", region: "América Central" },
  HU: { name: "Hungría", region: "Europa" },
  ID: { name: "Indonesia", region: "Asia" },
  IE: { name: "Irlanda", region: "Europa" },
  IL: { name: "Israel", region: "Asia" },
  IM: { name: "Isla de Man", region: "Europa" },
  IN: { name: "India", region: "Asia" },
  IO: { name: "Territorio Británico del Océano Índico", region: "Asia" },
  IQ: { name: "Irak", region: "Asia" },
  IR: { name: "Irán", region: "Asia" },
  IS: { name: "Islandia", region: "Europa" },
  IT: { name: "Italia", region: "Europa" },
  JE: { name: "Jersey", region: "Europa" },
  JM: { name: "Jamaica", region: "América Central" },
  JO: { name: "Jordania", region: "Asia" },
  JP: { name: "Japón", region: "Asia" },
  KE: { name: "Kenia", region: "África" },
  KG: { name: "Kirguistán", region: "Asia" },
  KH: { name: "Camboya", region: "Asia" },
  KI: { name: "Kiribati", region: "Oceanía" },
  KM: { name: "Comoras", region: "África" },
  KN: { name: "San Cristóbal y Nieves", region: "América Central" },
  KP: { name: "Corea del Norte", region: "Asia" },
  KR: { name: "Corea del Sur", region: "Asia" },
  KW: { name: "Kuwait", region: "Asia" },
  KY: { name: "Islas Caimán", region: "América Central" },
  KZ: { name: "Kazajistán", region: "Asia" },
  LA: { name: "Laos", region: "Asia" },
  LB: { name: "Líbano", region: "Asia" },
  LC: { name: "Santa Lucía", region: "América Central" },
  LI: { name: "Liechtenstein", region: "Europa" },
  LK: { name: "Sri Lanka", region: "Asia" },
  LR: { name: "Liberia", region: "África" },
  LS: { name: "Lesoto", region: "África" },
  LT: { name: "Lituania", region: "Europa" },
  LU: { name: "Luxemburgo", region: "Europa" },
  LV: { name: "Letonia", region: "Europa" },
  LY: { name: "Libia", region: "África" },
  MA: { name: "Marruecos", region: "África" },
  MC: { name: "Mónaco", region: "Europa" },
  MD: { name: "Moldavia", region: "Europa" },
  ME: { name: "Montenegro", region: "Europa" },
  MF: { name: "San Martín", region: "América Central" },
  MG: { name: "Madagascar", region: "África" },
  MH: { name: "Islas Marshall", region: "Oceanía" },
  MK: { name: "Macedonia del Norte", region: "Europa" },
  ML: { name: "Malí", region: "África" },
  MM: { name: "Myanmar", region: "Asia" },
  MN: { name: "Mongolia", region: "Asia" },
  MO: { name: "Macao", region: "Asia" },
  MP: { name: "Islas Marianas del Norte", region: "Oceanía" },
  MQ: { name: "Martinica", region: "América Central" },
  MR: { name: "Mauritania", region: "África" },
  MS: { name: "Montserrat", region: "América Central" },
  MT: { name: "Malta", region: "Europa" },
  MU: { name: "Mauricio", region: "África" },
  MV: { name: "Maldivas", region: "Asia" },
  MW: { name: "Malaui", region: "África" },
  MX: { name: "México", region: "América del Norte" },
  MY: { name: "Malasia", region: "Asia" },
  MZ: { name: "Mozambique", region: "África" },
  NA: { name: "Namibia", region: "África" },
  NC: { name: "Nueva Caledonia", region: "Oceanía" },
  NE: { name: "Níger", region: "África" },
  NF: { name: "Isla Norfolk", region: "Oceanía" },
  NG: { name: "Nigeria", region: "África" },
  NI: { name: "Nicaragua", region: "América Central" },
  NL: { name: "Países Bajos", region: "Europa" },
  NO: { name: "Noruega", region: "Europa" },
  NP: { name: "Nepal", region: "Asia" },
  NR: { name: "Nauru", region: "Oceanía" },
  NU: { name: "Niue", region: "Oceanía" },
  NZ: { name: "Nueva Zelanda", region: "Oceanía" },
  OM: { name: "Omán", region: "Asia" },
  PA: { name: "Panamá", region: "América Central" },
  PE: { name: "Perú", region: "América del Sur" },
  PF: { name: "Polinesia Francesa", region: "Oceanía" },
  PG: { name: "Papúa Nueva Guinea", region: "Oceanía" },
  PH: { name: "Filipinas", region: "Asia" },
  PK: { name: "Pakistán", region: "Asia" },
  PL: { name: "Polonia", region: "Europa" },
  PM: { name: "San Pedro y Miquelón", region: "América del Norte" },
  PN: { name: "Islas Pitcairn", region: "Oceanía" },
  PR: { name: "Puerto Rico", region: "América Central" },
  PS: { name: "Palestina", region: "Asia" },
  PT: { name: "Portugal", region: "Europa" },
  PW: { name: "Palaos", region: "Oceanía" },
  PY: { name: "Paraguay", region: "América del Sur" },
  QA: { name: "Catar", region: "Asia" },
  RE: { name: "Reunión", region: "África" },
  RO: { name: "Rumania", region: "Europa" },
  RS: { name: "Serbia", region: "Europa" },
  RU: { name: "Rusia", region: "Europa/Asia" },
  RW: { name: "Ruanda", region: "África" },
  SA: { name: "Arabia Saudita", region: "Asia" },
  SB: { name: "Islas Salomón", region: "Oceanía" },
  SC: { name: "Seychelles", region: "África" },
  SD: { name: "Sudán", region: "África" },
  SE: { name: "Suecia", region: "Europa" },
  SG: { name: "Singapur", region: "Asia" },
  SH: { name: "Santa Elena", region: "África" },
  SI: { name: "Eslovenia", region: "Europa" },
  SJ: { name: "Svalbard y Jan Mayen", region: "Europa" },
  SK: { name: "Eslovaquia", region: "Europa" },
  SL: { name: "Sierra Leona", region: "África" },
  SM: { name: "San Marino", region: "Europa" },
  SN: { name: "Senegal", region: "África" },
  SO: { name: "Somalia", region: "África" },
  SR: { name: "Surinam", region: "América del Sur" },
  SS: { name: "Sudán del Sur", region: "África" },
  ST: { name: "Santo Tomé y Príncipe", region: "África" },
  SV: { name: "El Salvador", region: "América Central" },
  SX: { name: "Sint Maarten", region: "América Central" },
  SY: { name: "Siria", region: "Asia" },
  SZ: { name: "Suazilandia", region: "África" },
  TC: { name: "Islas Turcas y Caicos", region: "América Central" },
  TD: { name: "Chad", region: "África" },
  TF: { name: "Territorios Australes Franceses", region: "Antártida" },
  TG: { name: "Togo", region: "África" },
  TH: { name: "Tailandia", region: "Asia" },
  TJ: { name: "Tayikistán", region: "Asia" },
  TK: { name: "Tokelau", region: "Oceanía" },
  TL: { name: "Timor Oriental", region: "Asia" },
  TM: { name: "Turkmenistán", region: "Asia" },
  TN: { name: "Túnez", region: "África" },
  TO: { name: "Tonga", region: "Oceanía" },
  TR: { name: "Turquía", region: "Europa/Asia" },
  TT: { name: "Trinidad y Tobago", region: "América Central" },
  TV: { name: "Tuvalu", region: "Oceanía" },
  TW: { name: "Taiwán", region: "Asia" },
  TZ: { name: "Tanzania", region: "África" },
  UA: { name: "Ucrania", region: "Europa" },
  UG: { name: "Uganda", region: "África" },
  UM: { name: "Islas Ultramarinas Menores de EE.UU.", region: "Oceanía" },
  US: { name: "Estados Unidos", region: "América del Norte" },
  UY: { name: "Uruguay", region: "América del Sur" },
  UZ: { name: "Uzbekistán", region: "Asia" },
  VA: { name: "Ciudad del Vaticano", region: "Europa" },
  VC: { name: "San Vicente y las Granadinas", region: "América Central" },
  VE: { name: "Venezuela", region: "América del Sur" },
  VG: { name: "Islas Vírgenes Británicas", region: "América Central" },
  VI: { name: "Islas Vírgenes de EE.UU.", region: "América Central" },
  VN: { name: "Vietnam", region: "Asia" },
  VU: { name: "Vanuatu", region: "Oceanía" },
  WF: { name: "Wallis y Futuna", region: "Oceanía" },
  WS: { name: "Samoa", region: "Oceanía" },
  XK: { name: "Kosovo", region: "Europa" },
  xk: { name: "Kosovo", region: "Europa" },
  YE: { name: "Yemen", region: "Asia" },
  YT: { name: "Mayotte", region: "África" },
  ZA: { name: "Sudáfrica", region: "África" },
  ZM: { name: "Zambia", region: "África" },
  ZW: { name: "Zimbabue", region: "África" },
};

function resolveCountryName(code: string) {
  const override = COUNTRY_OVERRIDES[code];
  if (override) {
    return override.name;
  }
  const normalized = code.length === 2 ? code.toUpperCase() : code.toUpperCase();
  try {
    const displayNames = new Intl.DisplayNames(["es"], { type: "region" });
    const label = displayNames.of(normalized);
    return label ?? code;
  } catch {
    return code;
  }
}

function resolveRegion(code: string) {
  const override = COUNTRY_OVERRIDES[code];
  return override?.region ?? "Otros";
}

export const COUNTRIES: CountryInfo[] = FLAG_CODES.map((code) => {
  return {
    code,
    name: resolveCountryName(code),
    region: resolveRegion(code),
  };
});

export const COUNTRY_BY_CODE: Record<string, CountryInfo> = COUNTRIES.reduce(
  (acc, country) => {
    acc[country.code] = country;
    return acc;
  },
  {} as Record<string, CountryInfo>
);

// NUEVO: Helper para garantizar que las banderas carguen desde la URL pública
export function getFlagSrc(code: string) {
  return buildAssetUrl(`/flags/SVG/${code}.svg`);
}
